### ISSUE TITLE
Unnecessary dependencies

### ISSUE THREAD

**Issue by nucliweb** [nakDS/nakds#5]
You don't need these [dependencies](https://github.com/nabaroa/nak-scaffold/blob/master/package.json#L25-L41)

```
    "autoprefixer": "^9.7.1",
    "postcss-custom-media": "^7.0.8",
    "postcss-custom-properties": "^9.0.2",
    "postcss-nested": "^4.2.1",
```

Yhey are as a dependency in [postcss-preset-env](https://github.com/csstools/postcss-preset-env/blob/master/package.json#L30)

**Comment by nabaroa** [comment]
Yey! Thanks @nucliweb =^_^=
Fixed.
